express = require('express')
router = express.Router()
app = express()

bodyParser = require('body-parser')
coffeeMiddleware = require('coffee-middleware')

PORT = process.env.PORT

# sets up coffee-script support

app.use coffeeMiddleware
  bare: true
  src: "public"
require('coffee-script/register')

app.use bodyParser.urlencoded
  extended: false
app.use bodyParser.json()
app.use bodyParser.text()

app.listen PORT, ->
  console.log "Your app is running on #{PORT}"

routes = require('./routes')(router)

app.use '/', router

# ---
# generated by js2coffee 2.2.0